### ISSUE TITLE
Input data format descend

### ISSUE THREAD

**Issue by ogrosko** [MAXakaWIZARD/JsonCollectionParser#10]
Hello,

Is it possible to descend in JSON structure? Suppose I have data format like:

```
         {
            "objects": [
                {
                    "uid": 1,
                    "name": "Name 1"
                },
                {
                    "uid": 2,
                    "name": "Name 2"
                }
            ]
        }
```

So I can walk through the objects items
Thank you

**Comment by MAXakaWIZARD** [comment]
@ogrosko the structure you provided is not supported - you have to put commas between your objects like this:
```
{
            "objects": [
                {
                    "uid": 1,
                    "name": "Name 1"
                },
                {
                    "uid": 2,
                    "name": "Name 2"
                }
            ]
        }
```

**Comment by ogrosko** [comment]
@MAXakaWIZARD woops sorry, typo in my example json. I already fixed it.
But my question is: whether I can iterate over `"objects"`. 
In other words: When I want to iterate over objects I have to strip `"objects"` from the json and then It gives me results as expected. 
So I have to JSON like this:

```
                {
                    "uid": 1,
                    "name": "Name 1"
                },
                {
                    "uid": 2,
                    "name": "Name 2"
                }
```

**Comment by MAXakaWIZARD** [comment]
@ogrosko at the moment iterating over objects is supported only for root-level objects
