### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by nikazooz** [MAXakaWIZARD/JsonCollectionParser#11]
Hi :wave: 

I've noticed that support for PHP8 is implemented, but not released even though CHANGELOG mentions v1.8.0.

Just wanted to see if there is a plan to release a new version with PHP8 support soon?

Thanks for your work on this great package! Cheers!

**Comment by MAXakaWIZARD** [comment]
@nikazooz PHP 8 support was blocked by some dependency back then. I will check everything today or tomorrow and release new version.

**Comment by MAXakaWIZARD** [comment]
Version 1.8.0 has been released: https://github.com/MAXakaWIZARD/JsonCollectionParser/releases/tag/1.8.0

**Comment by nikazooz** [comment]
Great news! 🙂 Thank you!
