### ISSUE TITLE
500mb json file timeout error

### ISSUE THREAD

**Issue by kLOsk** [MAXakaWIZARD/JsonCollectionParser#7]
I have a 500mb json file, which is also available here (https://archive.scryfall.com/json/scryfall-all-cards.json) When I'm trying to process this file I need to raise max execution time to something like 1000 seconds as otherwise I receive timeout in the salsify parser.

Is there any way to solve this? I mean it's great, that the files is not loaded into memory, but many servers don't allow for raising execution time to insane values neither?

The error hits at Parser.php Line 152, 197, or 201.

Thanks

**Comment by MAXakaWIZARD** [comment]
hey @kLOsk! What else are you doing besides parsing data? Maybe you are inserting records into DB or something?

**Comment by kLOsk** [comment]
@MAXakaWIZARD thanks for the reply, no I actually just wanted to echo some data like so:

`<?php
        $testfile = get_template_directory().'/jsontest/scryfall-all-cards.json'; //https://gist.github.com/soyuka/a1d83ff9ff1a6c5cc269
     
        function processItem(array $item)
        {
           
            if ($item['object'] == 'card' && $item['name'] == 'Blue Ward') {
              echo $item['oracle_id'];//fc0bf1d0-46a2-4305-ab2e-466d79d60ab2
              echo '<br />';
            }

        }

        $parser = new \JsonCollectionParser\Parser();
        $parser->parse($testfile, 'processItem'); ?>`

Tho it made me thinking a parser solves the issue to load all data in memory, but the php script is still bound to processing all the data. so I would need to somehow background process the parsing instead of running it on a server call?

**Comment by Ocramius** [comment]
@kLOsk as far as I understand (and am currently testing) this tool performs memory-constant parsing, but no time constraints are enforced.

Even if you do increase PHP's timeout settings, the client may long be gone when you provide a response: background processing is very much unavoidable.

(yep, I know this is old - just happened to start using this library :-) )

**Comment by MAXakaWIZARD** [comment]
@Ocramius any input from you is highly appreciated ;)

**Comment by Ocramius** [comment]
@MAXakaWIZARD thanks! I think this can be closed BTW :+1:
